### ISSUE TITLE
system call not working as expected

### ISSUE THREAD

**Issue by SantiParagarino** [graphp/graphviz#63]
When calling the PHP function systemcall on https://github.com/graphp/graphviz/blob/master/src/GraphViz.php#L210
it returns as if an error happened due to dot program returning the response on the STDERR value even when it is not an error.

In order to solve this simply add **2>&1** at the end of the command like this:

```php
system(escapeshellarg($executable) . ' -T ' . escapeshellarg($this->format) . ' ' . escapeshellarg($tmp) . ' -o ' . escapeshellarg($tmp . '.' . $this->format) . ' 2>&1', $ret)
```

**Comment by SimonFrings** [comment]
Hey @Santiagoebizmarts, thanks for bringing this up :+1: 

I would ask the question: Is it useful to just add `2>&1`, this will write everything from `STDERR` to `STDOUT`.

I am curious tho, this could be something caused by Graphviz itself or **maybe** a bug in this project (unlikely but still possible). Can you give me a bit more information on what you're trying to do and what your output looks like (code examples would be great :+1:)

**Comment by clue** [comment]
I'm closing this for now due to a lack of feedback, as we can not reproduce this. Please come back with more details if this problem persists and we can always reopen this :+1:
